# Fix line endings on Windows
init:
  - git config --global core.autocrlf true
# What combinations to test
environment:
  matrix:
    - nodejs_version: "0.12"
platform:
  - x86
  - x64
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install grunt-cli -g
  - npm install
  - grunt travis
#build: off
test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  - tsc -v
matrix:
  fast_finish: true
cache:
  - C:\Users\appveyor\AppData\Roaming\npm\node_modules -> package.json  # global npm modules
  - C:\Users\appveyor\AppData\Roaming\npm-cache -> package.json         # npm cache
  - node_modules -> package.json                                        # local npm modules